"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { FeeList } from "@/components/fees/fee-list";
import { requestJson } from "@/lib/admin/client";
import { formatAfghani } from "@/lib/fees/money";
import type { FeeRow } from "@/lib/fees/data";
type Setup = Awaited<ReturnType<typeof import("@/lib/fees/data").getFeeSetup>>;
type Section = "records" | "add-fee" | "record-payment" | "fee-types";
const controlClass = "h-10 w-full rounded-md border bg-background px-3 text-sm";

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="grid gap-1.5 text-sm font-medium">{label}{children}</label>;
}

export function FeeManagement({ initialSetup, initialFees }: { initialSetup: Setup; initialFees: { items: FeeRow[]; total: number; page: number; pageSize: number } }) {
  const cache = useQueryClient();
  const [section, setSection] = useState<Section>("records");
  const fees = useQuery({ queryKey: ["fees"], queryFn: () => requestJson<typeof initialFees>("/api/admin/fees"), initialData: initialFees });
  const submit = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => requestJson(path, { method: "POST", body: JSON.stringify(body) }), onSuccess: () => cache.invalidateQueries({ queryKey: ["fees"] }), onError: (cause) => toast.error(cause.message) });
  const today = new Date().toISOString().slice(0, 10);
  const outstandingFees = (fees.data?.items ?? []).filter((fee) => fee.balance > 0);
  const save = (path: string, body: unknown, successMessage: string, form: HTMLFormElement) => submit.mutate({ path, body }, { onSuccess: () => { toast.success(successMessage); form.reset(); cache.invalidateQueries({ queryKey: ["fees"] }); setSection("records"); } });
  const navigation: Array<{ id: Section; label: string }> = [{ id: "records", label: "Fee records" }, { id: "add-fee", label: "Add fee" }, { id: "record-payment", label: "Record payment" }, { id: "fee-types", label: "Fee types" }];

  return <div className="space-y-6">
    <nav className="flex flex-wrap gap-2" aria-label="Fee tasks">{navigation.map((item) => <Button key={item.id} type="button" variant={section === item.id ? "default" : "outline"} onClick={() => setSection(item.id)}>{item.label}</Button>)}</nav>
    {section === "records" ? <section className="space-y-4"><div><h2 className="font-semibold">Fee records</h2><p className="mt-1 text-sm text-muted-foreground">Review what is due, what has been paid, and the remaining balance.</p></div><FeeList fees={fees.data?.items ?? []} showStudent /></section> : null}
    {section === "add-fee" ? <section className="max-w-3xl rounded-lg border bg-card p-5"><h2 className="font-semibold">Add a fee for a student</h2><p className="mt-1 text-sm text-muted-foreground">Choose the student and fee, then enter the amount in Afghan afghani (AFN).</p><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); save("/api/admin/fees/records", { studentId: form.get("studentId"), feeTypeId: form.get("feeTypeId"), academicYearId: form.get("academicYearId"), termId: form.get("termId"), amountDue: form.get("amountDue"), dueDate: form.get("dueDate"), notes: form.get("notes") }, "Fee record added.", event.currentTarget); }}><Field label="Student"><select name="studentId" className={controlClass} required><option value="">Choose a student</option>{initialSetup.students.map((student) => <option key={student.id} value={student.id}>{student.name} · {student.admissionNumber}</option>)}</select></Field><Field label="Fee type"><select name="feeTypeId" className={controlClass} required><option value="">Choose a fee type</option>{initialSetup.types.filter((type) => type.isActive).map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></Field><Field label="Academic year"><select name="academicYearId" className={controlClass} required defaultValue={initialSetup.years.find((year) => year.status === "current")?.id}><option value="">Choose an academic year</option>{initialSetup.years.map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select></Field><Field label="Term (optional)"><select name="termId" className={controlClass}><option value="">No term</option>{initialSetup.terms.map((term) => <option key={term.id} value={term.id}>{term.name}</option>)}</select></Field><Field label="Amount due (AFN)"><Input name="amountDue" type="number" min="0" step="0.01" placeholder="For example: 2500" required /></Field><Field label="Due date"><Input name="dueDate" type="date" defaultValue={today} required /></Field><Field label="Note (optional)"><Input name="notes" placeholder="For example: September tuition" /></Field><div className="flex items-end"><Button disabled={submit.isPending} className="w-full">Add fee</Button></div></form></section> : null}
    {section === "record-payment" ? <section className="max-w-3xl rounded-lg border bg-card p-5"><h2 className="font-semibold">Record a payment</h2><p className="mt-1 text-sm text-muted-foreground">Select an outstanding fee and enter the payment received. Payments cannot exceed the remaining balance.</p>{outstandingFees.length ? <form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); save("/api/admin/fees/payments", { feeRecordId: form.get("feeRecordId"), amount: form.get("amount"), paidOn: form.get("paidOn"), paymentMethod: form.get("paymentMethod"), receiptNumber: form.get("receiptNumber"), notes: form.get("notes") }, "Payment recorded.", event.currentTarget); }}><Field label="Fee record"><select name="feeRecordId" className={controlClass} required><option value="">Choose an outstanding fee</option>{outstandingFees.map((fee) => <option key={fee.id} value={fee.id}>{fee.studentName} · {fee.feeType} · {formatAfghani(fee.balance)} remaining</option>)}</select></Field><Field label="Amount received (AFN)"><Input name="amount" type="number" min="0.01" step="0.01" placeholder="For example: 1000" required /></Field><Field label="Payment date"><Input name="paidOn" type="date" defaultValue={today} required /></Field><Field label="Payment method"><Input name="paymentMethod" defaultValue="Cash" required /></Field><Field label="Receipt or reference number"><Input name="receiptNumber" placeholder="For example: REC-001" required /></Field><Field label="Note (optional)"><Input name="notes" placeholder="Optional payment note" /></Field><div className="flex items-end"><Button disabled={submit.isPending} className="w-full">Save payment</Button></div></form> : <p className="mt-5 rounded-md border border-dashed p-4 text-sm text-muted-foreground">There are no outstanding fees to pay.</p>}</section> : null}
    {section === "fee-types" ? <section className="max-w-3xl rounded-lg border bg-card p-5"><h2 className="font-semibold">Fee types</h2><p className="mt-1 text-sm text-muted-foreground">Set up the kinds of fees the school charges before adding student fee records.</p><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); save("/api/admin/fees/types", { name: form.get("name"), description: form.get("description"), defaultAmount: form.get("defaultAmount"), frequency: form.get("frequency"), isActive: true, academicYearId: form.get("academicYearId") }, "Fee type added.", event.currentTarget); }}><Field label="Fee type name"><Input name="name" placeholder="For example: Monthly tuition" required /></Field><Field label="Usual amount (AFN)"><Input name="defaultAmount" type="number" min="0" step="0.01" placeholder="For example: 2500" required /></Field><Field label="How often is it charged?"><select name="frequency" className={controlClass}><option value="one_time">One time</option><option value="monthly">Monthly</option><option value="termly">Each term</option><option value="annual">Yearly</option></select></Field><Field label="Academic year (optional)"><select name="academicYearId" className={controlClass}><option value="">All academic years</option>{initialSetup.years.map((year) => <option key={year.id} value={year.id}>{year.name}</option>)}</select></Field><Field label="Description (optional)"><Input name="description" placeholder="A short note about this fee" /></Field><div className="flex items-end"><Button disabled={submit.isPending} className="w-full">Add fee type</Button></div></form><div className="mt-6 border-t pt-5"><h3 className="font-medium">Existing fee types</h3>{initialSetup.types.length ? <div className="mt-3 space-y-2">{initialSetup.types.map((type) => <p key={type.id} className="rounded-md border p-3 text-sm"><span className="font-medium">{type.name}</span> · {type.frequency.replace("_", " ")} · usual amount {formatAfghani(type.defaultAmount)}</p>)}</div> : <p className="mt-3 text-sm text-muted-foreground">No fee types have been created yet.</p>}</div></section> : null}
  </div>;
}
